### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by AmirolAhmad** [amree/teecket-web#11]
Any idea why?

https://teecket.herokuapp.com/KUL/KNO/30-06-2015

![screen shot 2015-06-22 at 12 40 50 am](https://cloud.githubusercontent.com/assets/1130863/8272501/5a6bd2e6-1877-11e5-85a1-4d621d815df0.png)

**Comment by amree** [comment]
The logs said it was a request time out. It's either from Heroku configs or Sinatra itself. I'm not sure which one yet. But it's definitely not from the gem as the gem would just return empty array when there's an error (I've also tested it by running the gem manually).

Needs further investigation. This happened due to AirAsia's promotion (you've probably guess that one, lol)
